### ISSUE TITLE
JNI Error 

### ISSUE THREAD

**Issue by LunarstarFurry** [Araxeus/PNG-Upscale#33]
System: Windows 10
When I try to start the Exe file and windows pop up said Error: A JNI error has occurred, please check your installation and try again, this happened on both Jar and exe.
![2021-08-26_14-46-57](https://user-images.githubusercontent.com/36251959/130914583-9dbbb19e-48b1-478e-8b6f-69e5ad0d2159.png)

**Comment by EarthenSky** [comment]
Hey, I also had this error & this thread really helped! I think it would be helpful to pin or allude to this error somewhere on the readme.

**Comment by Araxeus** [comment]
> Hey, I also had this error & this thread really helped! I think it would be helpful to pin or allude to this error somewhere on the readme.

done :)

**Comment by radegeddon** [comment]
Run CMD> java -jar png-upscale-1.0_Windows64bit.jar

If you get this error:
"_Exception in thread "main" java.lang.UnsupportedClassVersionError: core/MainApp has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to ..._"

You need to install Java SE v15 or higher, as indicated in this table that shows the mapping between Java SE Version and Major Version:
Java SE   Major version
1.0.2     45
1.1       45
1.2       46
1.3       47
1.4       48
5.0       49
6          50
7          51
8          52
9          53
10        54
11        55
12        56
13        57
14        58
15        59
16        60
17        61
18        62
19        63
20        64
21        65

The table is taken from:
https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-4.html
https://javaalmanac.io/bytecode/versions/

java.exe executable is in C:\Program Files\Java\jdk-21\bin directory, so that is what you need to have in PATH.

Use Rapid Environment Editor tool (https://www.rapidee.com) to quickly verify or edit the environment variables on Windows.
It allows to reorder PATH entries. It will also highlight invalid paths in red.

The solution is to have Java 15 (or higher) bin directory in PATH or above instead of Java 8. On Windows you may have C:\Program Files (x86)\Common Files\Oracle\Java\javapath added to PATH automatically which points to Java 8.

If that is the case, remove the Java 8 part from PATH and then logout/login or reboot for the changes to have effect.
